# Generated by Django 4.0.4 on 2022-05-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_alter_cadeira_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='image',
            field=models.ImageField(default='\\images\\default.png', upload_to='images'),
        ),
    ]
