# Generated by Django 4.0.4 on 2022-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_questao_cadeira'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='titulo',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
