# Generated by Django 4.0.4 on 2022-05-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uid',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
